const students = [ 
    {
        firstName: "Harry",
        lastName: "Potter",
        age: "17",
        year: "7",
        photo: "harrypotter.jpg",
        hiddenDetail: "Harry can speak Parseltongue",
},
{
        firstName: "Hermione",
        lastName: "Granger",
        age: "17",
        year: "7",
        photo: "granger.jpg",
        hiddenDetail: "Hermione memorized any Hogwarts test",
},
{
        firstName: "Ron",
        lastName: "Weasley",
        age: "17",
        year: "7",
        photo: "ron.jpg",
        hiddenDetail: "Ron is terrified of spiders",
},
{
        firstName: "Neville",
        lastName: "Longbottom",
        age: "17",
        year: "7",
        photo: "neville.jpeg",
        hiddenDetail: "Neville eventually became a Hogwarts professor",
},
{
        firstName: "Ginny",
        lastName: "Weasley",
        age: "16",
        year: "6",
        photo: "ginny.jpg",
        hiddenDetail: "She married Harry Potter and had three children; James Sirius, Albus Severus, & Lily Luna",
},
{
        firstName: "Fred",
        lastName: "Weasley",
        age: "20",
        year: "N/A",
        photo: "fred.png",
        hiddenDetail: "Fred is the older brother",
},
{
        firstName: "George",
        lastName: "Weasley",
        age: "20",
        year: "N/A",
        photo: "george.png",
        hiddenDetail: "During the Battle of the Seven Potters, George lost his left ear after being struck by Severus Snape's",
},
{
        firstName: "Dean",
        lastName: "Thomas",
        age: "17",
        year: "7",
        photo: "dean.jpg",
        hiddenDetail: "Dated Ginny Weasley for a period, though the relationship ended due to the stress of her rising confidence and an awkward encounter involving an invisible Harry Potter.",
},
{
        firstName: "Seamus",
        lastName: "Finnigan",
        age: "17",
        year: "7",
        photo: "finn.jpg",
        hiddenDetail: "Infamous for his accidental explosions. From setting his feather on fire in Charms class to repeatedly blowing up his cauldrons",
},
{
        firstName: "Oliver",
        lastName: "Wood",
        age: "17",
        year: "7",
        photo: "oliver.jpg",
        hiddenDetail: "Oliver wore a pair of lucky socks—given to him by his grandmother—for every single match he played at Hogwarts",
},
{
        firstName: "Albus",
        lastName: "Dumbledore",
        age: "115",
        year: "Mentor",
        photo: "dumbledore.jpg",
        hiddenDetail: "Dumbledore is an old 18th-century English word for bumblebee. J.K. Rowling chose the name because she liked to imagine Albus wandering the castle, humming to himself",
},
{
        firstName: "Minerva",
        lastName: "McGonagall",
        age: "91",
        year: "Mentor",
        photo: "minerva.jpg",
        hiddenDetail: "After school, she fell in love with a Muggle farmer named Dougal McGregor. She broke off the engagement to avoid hiding her magical abilities but never stopped loving him",
},
{
        firstName: "Rubeus",
        lastName: "Hagrid",
        age: "62",
        year: "Mentor",
        photo: "rubeus.jpg",
        hiddenDetail: " Due to his giant blood, he is highly resistant to Stunning spells, but this also means he is too large to ride a broomstick and is entirely incapable of producing a Patronus",
},
{
        firstName: "Sirius",
        lastName: "Black",
        age: "36",
        year: "N/A",
        photo: "black.jpg",
        hiddenDetail: "J.K. Rowling cried after writing his death scene",
},
{
        firstName: "Remus",
        lastName: "Lupin",
        age: "38",
        year: "Mentor",
        photo: "lupin.jpg",
        hiddenDetail: " His name is a direct nod to his condition—Remus from the Roman myth of Romulus and Remus (raised by wolves), and Lupin from the Latin lupus",
},
];
