const houses = { 
    gryffindor: [ 
        {
        firstName: "Harry",
        lastName: "Potter",
        age: "17",
        year: "7",
        photo: "imgs/harrypotter.jpg",
        hiddenDetail: "Harry can speak Parseltongue",
    },
{
        firstName: "Hermione",
        lastName: "Granger",
        age: "17",
        year: "7",
        photo: "imgs/granger.jpg",
        hiddenDetail: "Hermione memorized any Hogwarts test",
},
{
        firstName: "Ron",
        lastName: "Weasley",
        age: "17",
        year: "7",
        photo: "imgs/ron.jpg",
        hiddenDetail: "Ron is terrified of spiders",
},
{
        firstName: "Neville",
        lastName: "Longbottom",
        age: "17",
        year: "7",
        photo: "imgs/neville.jpeg",
        hiddenDetail: "Neville eventually became a Hogwarts professor",
},
{
        firstName: "Ginny",
        lastName: "Weasley",
        age: "16",
        year: "6",
        photo: "imgs/ginny.jpg",
        hiddenDetail: "She married Harry Potter and had three children; James Sirius, Albus Severus, & Lily Luna",
},
{
        firstName: "Fred",
        lastName: "Weasley",
        age: "20",
        year: "N/A",
        photo: "imgs/fred.png",
        hiddenDetail: "Fred is the older brother",
},
{
        firstName: "George",
        lastName: "Weasley",
        age: "20",
        year: "N/A",
        photo: "imgs/george.png",
        hiddenDetail: "During the Battle of the Seven Potters, George lost his left ear after being struck by Severus Snape's",
},
{
        firstName: "Dean",
        lastName: "Thomas",
        age: "17",
        year: "7",
        photo: "imgs/dean.jpg",
        hiddenDetail: "Dated Ginny Weasley for a period, though the relationship ended due to the stress of her rising confidence and an awkward encounter involving an invisible Harry Potter.",
},
{
        firstName: "Seamus",
        lastName: "Finnigan",
        age: "17",
        year: "7",
        photo: "imgs/finn.jpg",
        hiddenDetail: "Infamous for his accidental explosions. From setting his feather on fire in Charms class to repeatedly blowing up his cauldrons",
},
{
        firstName: "Oliver",
        lastName: "Wood",
        age: "17",
        year: "7",
        photo: "imgs/oliver.jpg",
        hiddenDetail: "Oliver wore a pair of lucky socks—given to him by his grandmother—for every single match he played at Hogwarts",
},
{
        firstName: "Albus",
        lastName: "Dumbledore",
        age: "115",
        year: "Mentor",
        photo: "imgs/dumbledore.jpg",
        hiddenDetail: "Dumbledore is an old 18th-century English word for bumblebee. J.K. Rowling chose the name because she liked to imagine Albus wandering the castle, humming to himself",
},
{
        firstName: "Minerva",
        lastName: "McGonagall",
        age: "91",
        year: "Mentor",
        photo: "imgs/minerva.jpg",
        hiddenDetail: "After school, she fell in love with a Muggle farmer named Dougal McGregor. She broke off the engagement to avoid hiding her magical abilities but never stopped loving him",
},
{
        firstName: "Rubeus",
        lastName: "Hagrid",
        age: "62",
        year: "Mentor",
        photo: "imgs/rubeus.jpg",
        hiddenDetail: " Due to his giant blood, he is highly resistant to Stunning spells, but this also means he is too large to ride a broomstick and is entirely incapable of producing a Patronus",
},
{
        firstName: "Sirius",
        lastName: "Black",
        age: "36",
        year: "N/A",
        photo: "imgs/black.jpg",
        hiddenDetail: "J.K. Rowling cried after writing his death scene",
},
{
        firstName: "Remus",
        lastName: "Lupin",
        age: "38",
        year: "Mentor",
        photo: "imgs/lupin.jpg",
        hiddenDetail: " His name is a direct nod to his condition—Remus from the Roman myth of Romulus and Remus (raised by wolves), and Lupin from the Latin lupus",
}],
hufflepuff: [
        {
        firstName: "Cedric",
        lastName: "Diggory",
        age: "17",
        year: "N/A",
        photo: "imgs/cedric.png",
        hiddenDetail: "Cedric was known for his fairness and integrity",
},
{
        firstName: "Nymphadora",
        lastName: "Tonks",
        age: "25",
        year: "N/A",
        photo: "imgs/nymphadora.jpeg",
        hiddenDetail: "Nymphadora was known for her ability to transform into any animal she desired",
},
{
        firstName: "Newt",
        lastName: "Scamander",
        age: "100",
        year: "N/A",
        photo: "imgs/newt.jpg",
        hiddenDetail: "Newt was known for his ability to communicate with and care for magical creatures",
},
{
        firstName: "Pomona",
        lastName: "Sprout",
        age: "60",
        year: "mentor",
        photo: "imgs/sprout.jpg",
        hiddenDetail: "Pomona was known for her expertise in Herbology and her love for teaching",
},
{
        firstName: "Theseus",
        lastName: "Scamander",
        age: "108",
        year: "N/A",
        photo: "imgs/theseus.jpg",
        hiddenDetail: "Theseus was known for his bravery and leadership skills",
},
{
        firstName: "Hannah",
        lastName: "Abbott",
        age: "17",
        year: "7",
        photo: "imgs/hannah.png",
        hiddenDetail: "Hannah was known for her ability to transform into any animal she desired",
},
{
        firstName: "Ernie",
        lastName: "Macmillan",
        age: "17",
        year: "7",
        photo: "imgs/ernie.jpeg",
        hiddenDetail: "Ernie was known for his loyalty and dedication to his friends",
},
{
        firstName: "Susan",
        lastName: "Bones",
        age: "17",
        year: "7",
        photo: "imgs/susan.jpg",
        hiddenDetail: "Susan was known for her intelligence and academic excellence",
},
{
        firstName: "Justin",
        lastName: "Finch-Fletchley",
        age: "17",
        year: "7",
        photo: "imgs/justin.jpeg",
        hiddenDetail: "Justin was known for his loyalty and dedication to his friends",
},
{
        firstName: "Fat",
        lastName: "Friar",
        age: "N/A",
        year: "N/A",
        photo: "imgs/fat.jpg",
        hiddenDetail: "Fat was known for his kindness and gentle nature",
},
],
  ravenclaw: [ 
        {
        firstName: "Luna",
        lastName: "Lovegood",
        age: "17",
        year: "7",
        photo: "imgs/luna.jpeg",
        hiddenDetail: "Luna was known for her unique perspective and belief in the existence of creatures like Crumple-Horned Snorkacks",
},
{
        firstName: "Cho",
        lastName: "Chang",
        age: "18",
        year: "N/A",
        photo: "imgs/chang.jpg",
        hiddenDetail: "Cho was known for her beauty and skill in Herbology",
},
{
        firstName: "Filius",
        lastName: "Flitwick",
        age: "70",
        year: "Mentor",
        photo: "imgs/filius.jpeg",
        hiddenDetail: "Filius was known for his expertise in Charms and his gentle nature",
},
{
        firstName: "Garrick",
        lastName: "Ollivander",
        age: "82",
        year: "Mentor",
        photo: "imgs/garrick.jpg",
        hiddenDetail: "Garrick was known for his expertise in wand-making and his gentle nature",
},
{
        firstName: "Sybill",
        lastName: "Trelawney",
        age: "47",
        year: "Mentor",
        photo: "imgs/sybill.jpg",
        hiddenDetail: "Sybill was known for her expertise in Divination and her ability to see the future",
},
{
        firstName: "Padma",
        lastName: "Patil",
        age: "17",
        year: "7",
        photo: "imgs/patil.jpg",
        hiddenDetail: "Padma was known for her dedication to her studies and her commitment to her house",
},
{
        firstName: "Marcus",
        lastName: "Belby",
        age: "18",
        year: "7",
        photo: "imgs/marcus.jpeg",
        hiddenDetail: "Marcus was known for his expertise in Divination and his ability to see the future",
},
{
        firstName: "Michael",
        lastName: "Corner",
        age: "17",
        year: "7",
        photo: "imgs/michael.jpg",
        hiddenDetail: "Michael was known for his expertise in Divination and his ability to see the future",
},
{
        firstName: "Terry",
        lastName: "Boot",
        age: "17",
        year: "7",
        photo: "imgs/terry.jpeg",
        hiddenDetail: "Terry was known for his expertise in Divination and his ability to see the future",
},
{
        firstName: "Myrtle",
        lastName: "Warren",
        age: "N/A",
        year: "N/A",
        photo: "imgs/myrtle.jpeg",
        hiddenDetail: "Myrtle was known for her expertise in Divination and her ability to see the future",
},
  ],
  slytherin: [ 
        {
        firstName: "Severus",
        lastName: "Snape",
        age: "37",
        year: "Mentor",
        photo: "imgs/snape.jpeg",
        hiddenDetail: "Severus was known for his expertise in Potions and his complex personality",
},
{
        firstName: "Draco",
        lastName: "Malfoy",
        age: "17",
        year: "7",
        photo: "imgs/draco.jpeg",
        hiddenDetail: "Draco was known for his skill in Potions and his complex personality",
},
{
        firstName: "Tom",
        lastName: "Riddle",
        age: "71",
        year: "N/A",
        photo: "imgs/tom.jpg",
        hiddenDetail: "Tom was known for his expertise in Potions and his complex personality",
},
{
        firstName: "Bellatrix",
        lastName: "Lestrange",
        age: "46",
        year: "N/A",
        photo: "imgs/bellatrix.jpg",
        hiddenDetail: "Bellatrix was known for her loyalty to Voldemort and her expertise in Dark Arts",
},
{
        firstName: "Horace",
        lastName: "Slughorn",
        age: "90",
        year: "Mentor",
        photo: "imgs/horace.jpg",
        hiddenDetail: "Horace was known for his expertise in Potions and his ability to nurture talented students",
},
{
        firstName: "Lucius",
        lastName: "Malfoy",
        age: "43",
        year: "N/A",
        photo: "imgs/lucius.jpg",
        hiddenDetail: "Lucius was known for his expertise in Dark Arts and his loyalty to Voldemort",
},
{
        firstName: "Narcissa",
        lastName: "Malfoy",
        age: "38",
        year: "N/A",
        photo: "imgs/narcissa.png",
        hiddenDetail: "Narcissa was known for her loyalty to her family and her expertise in Dark Arts",
},
{
        firstName: "Andromeda",
        lastName: "Tonks",
        age: "42",
        year: "N/A",
        photo: "imgs/tonks.png",
        hiddenDetail: "Andromeda was known for her expertise in Divination and her ability to see the future",
},
{
        firstName: "Regulus",
        lastName: "Black",
        age: "17",
        year: "N/A",
        photo: "imgs/regulus.jpeg",
        hiddenDetail: "Regulus was known for his loyalty to his family and his involvement in Dark Arts",
},
  ]
};
