const students = [ 
    {
        firstName: "Harry",
        lastName: "Potter",
        age: "17",
        year: "7",
        photo: "imgs/harrypotter.jpg",
        hiddenDetail: "Harry can speak Parseltongue",
},
{
        firstName: "Hermione",
        lastName: "Granger",
        age: "17",
        year: "7",
        photo: "imgs/hermione.jpg",
        hiddenDetail: "Hermione memorized any Hogwarts test",
},
{
        firstName: "Ron",
        lastName: "Weasley",
        age: "17",
        year: "7",
        photo: "imgs/ron.jpg",
        hiddenDetail: "Ron is terrified of spiders",
},
{
        firstName: "Neville",
        lastName: "Longbottom",
        age: "17",
        year: "7",
        photo: "imgs/neville.jpeg",
        hiddenDetail: "Neville eventually became a Hogwarts professor",
},
{
        firstName: "Ginny",
        lastName: "Weasley",
        age: "16",
        year: "6",
        photo: "imgs/ginny.jpg",
        hiddenDetail: "She married Harry Potter and had three children; James Sirius, Albus Severus, & Lily Luna",
},
{
        firstName: "Fred",
        lastName: "Weasley",
        age: "20",
        year: "N/A",
        photo: "imgs/fred.png",
        hiddenDetail: "Fred is the older brother",
},
{
        firstName: "George",
        lastName: "Weasley",
        age: "20",
        year: "N/A",
        photo: "imgs/george.png",
        hiddenDetail: "During the Battle of the Seven Potters, George lost his left ear after being struck by Severus Snape's",
},
{
        firstName: "Dean",
        lastName: "Thomas",
        age: "17",
        year: "7",
        photo: "imgs/dean.jpg",
        hiddenDetail: "Dated Ginny Weasley for a period, though the relationship ended due to the stress of her rising confidence and an awkward encounter involving an invisible Harry Potter.",
},
{
        firstName: "Seamus",
        lastName: "Finnigan",
        age: "17",
        year: "7",
        photo: "imgs/seamus.jpg",
        hiddenDetail: "Infamous for his accidental explosions. From setting his feather on fire in Charms class to repeatedly blowing up his cauldrons",
},

];
