const students = [ 
    {
        firstName: "Harry",
        lastName: "Potter",
        age: "17",
        year: "7",
        photo: "",
        hiddenDetail: "Harry can speak Parseltongue",
},
{
        firstName: "Hermione",
        lastName: "Granger",
        age: "17",
        year: "7",
        photo: "",
        hiddenDetail: "Hermione memorized any Hogwarts test",
},
{
        firstName: "Ron",
        lastName: "Weasley",
        age: "17",
        year: "7",
        photo: "",
        hiddenDetail: "Ron is terrified of spiders",
},
{
        firstName: "Neville",
        lastName: "Longbottom",
        age: "17",
        year: "7",
        photo: "",
        hiddenDetail: "Neville eventually became a Hogwarts professor",
},
{
        firstName: "Ginny",
        lastName: "Weasley",
        age: "16",
        year: "6",
        photo: "",
        hiddenDetail: "",
},
{
        firstName: "Fred",
        lastName: "Weasley",
        age: "20",
        year: "N/A",
        photo: "",
        hiddenDetail: "",
},
{
        firstName: "George",
        lastName: "Weasley",
        age: "20",
        year: "N/A",
        photo: "",
        hiddenDetail: "",
},
{
        firstName: "Dean",
        lastName: "Thomas",
        age: "17",
        year: "7",
        photo: "",
        hiddenDetail: "",
},
{
        firstName: "Seamus",
        lastName: "Finnigan",
        age: "17",
        year: "7",
        photo: "",
        hiddenDetail: "",
},

];